# Generated by Django 6.0.2 on 2026-02-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paper_images/')),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('label', models.CharField(blank=True, default='', help_text='LaTeX label for \\ref{}, e.g. fig:architecture', max_length=100)),
                ('width', models.FloatField(default=0.9, help_text='Width as fraction of column width (0.1 – 1.0)')),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.document')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
