# Generated by Django 6.0.2 on 2026-02-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paperimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperimage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api.section'),
        ),
    ]
