# Generated by Django 6.0.2 on 2026-03-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paperimage_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index_terms',
            field=models.CharField(blank=True, default='component, formatting, style, styling, insert', max_length=500),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_key', models.CharField(help_text='e.g., smith2023', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Short title for UI display', max_length=200)),
                ('bibtex', models.TextField(help_text='Raw BibTeX entry')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.document')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
