# Generated by Django 6.0.2 on 2026-03-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_index_terms_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If set, this is a subsection of the parent section.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='api.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('intro', 'Introduction'), ('related_work', 'Related Work'), ('methodology', 'Methodology'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('references', 'References')], default='custom', max_length=50),
        ),
    ]
