# Generated by Django 6.0.2 on 2026-06-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_section_parent_alter_section_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Reviewer', max_length=100)),
                ('text', models.TextField()),
                ('quote', models.CharField(blank=True, default='', max_length=500)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.section')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('label', models.CharField(blank=True, default='', help_text='LaTeX label for \\ref{}, e.g. tab:comparison', max_length=100)),
                ('content', models.TextField(default='[["Header 1", "Header 2"], ["Val 1", "Val 2"]]')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.document')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='api.section')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
