# Generated by Django 6.0.2 on 2026-06-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_papertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertable',
            name='style',
            field=models.CharField(choices=[('standard', 'Standard (Grid)'), ('booktabs', 'Three-line (Booktabs)'), ('no_vertical', 'No Vertical Lines'), ('minimal', 'Minimal')], default='standard', max_length=20),
        ),
    ]
