# Generated by Django 6.0.2 on 2026-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperimage',
            name='image',
        ),
        migrations.AddField(
            model_name='paperimage',
            name='filename',
            field=models.CharField(default='image.png', max_length=255),
        ),
        migrations.AddField(
            model_name='paperimage',
            name='image_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
