# Generated by Django 6.0.6 on 2026-06-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_collaborators_sectionlock_documentpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.document')),
            ],
            options={
                'unique_together': {('document', 'email')},
            },
        ),
    ]
