# Generated by Django 6.0.6 on 2026-06-29 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_documentinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commenters',
            field=models.ManyToManyField(blank=True, related_name='commentable_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentinvite',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('commenter', 'Commenter'), ('editor', 'Editor')], default='editor', max_length=20),
        ),
    ]
