# Generated by Django 6.0.2 on 2026-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_document_commenters_document_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.CharField(choices=[('ieee', 'IEEE'), ('acm', 'ACM'), ('elsevier', 'Elsevier'), ('springer-lncs', 'Springer LNCS'), ('apa', 'APA 7th Edition'), ('mla', 'MLA 9th Edition')], default='ieee', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='template_style',
            field=models.CharField(default='conference', max_length=30),
        ),
    ]
