# Generated by Django 6.0.2 on 2026-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_document_template_document_template_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_collaborators_to_export',
            field=models.BooleanField(default=False),
        ),
    ]
