# Generated by Django 6.0.2 on 2026-07-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_document_allow_collaborators_to_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
