# Generated by Django 6.0.2 on 2026-07-07 06:56

from django.db import migrations
from django.utils import timezone


def backfill_updated_at(apps, schema_editor):
    Section = apps.get_model('api', 'Section')
    Section.objects.filter(updated_at__isnull=True).update(updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_section_updated_at'),
    ]

    operations = [
        migrations.RunPython(backfill_updated_at, reverse_code=migrations.RunPython.noop),
    ]
